### ISSUE TITLE
成图效果错误

### ISSUE THREAD

**Issue by PLTea-c** [TTsdzb/koishi-plugin-maifriend-image#1]
![image](https://github.com/TTsdzb/koishi-plugin-maifriend-image/assets/134802318/42fbf2ea-9379-48bd-b20e-c9bae7a16ead)
如图，使用图片大小1MB，750*750
此外，头像框使用的图床需要科学上网才能访问，建议修改一下

**Comment by TTsdzb** [comment]
这个位置不对的问题不知道是什么原因，只在沙盒中出现，在QQ中正常。

图床问题已解决，现在插件从本地加载图片。更新至0.0.2版本即可。
